<?php

/* 
 * Copyright 2014 vertabelo.com
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

namespace Vertabelo\VertabeloPropel;

class TypeMapping {
    function getTypeMapping() {
        return ['bfile' => 'BLOB',
            'bigint' => 'BIGINT',
            'bigint(%)' => 'BIGINT',
            'bigint(%) unsigned' => 'BIGINT',
            'bigint unsigned' => 'BIGINT',
            'bigint(%) unsigned zerofill' => 'BIGINT',
            'bigint unsigned zerofill' => 'BIGINT',
            'bigint(%) zerofill' => 'BIGINT',
            'bigint zerofill' => 'BIGINT',
            'bigserial' => 'BIGINT',
            'binary' => 'BLOB',
            'binary(%)'  => 'BLOB',
            'binary_double'  => 'DOUBLE',
            'binary_float'  => 'FLOAT',
            'binary large object'  => 'BLOB',
            'binary large object(%)' => 'BLOB',
            'binary varying' => 'BLOB',
            'binary varying(%)' => 'BLOB',
            'binary varying(max)'=> 'BLOB',
            'bit' => 'TINYINT',
            'bit(%)' => 'TINYINT',
            'bit varying(%)'=> 'BLOB',
            'blob'  => 'BLOB',
            'blob(%)'  => 'BLOB',
            'bool' => 'BOOLEAN',
            'boolean' => 'BOOLEAN',
            'box' => 'OBJECT',
            'bytea' => 'BLOB',
            'char' => 'CHAR',
            'char(%)' => 'CHAR',
            'character' => 'CHAR',
            'character(%)' => 'CHAR',
            'character(% byte)' => 'CHAR',
            'character large object' => 'LONGVARCHAR',
            'character large object(%)' => 'LONGVARCHAR',
            'character varying' => 'VARCHAR',
            'character varying(%)' => 'VARCHAR',
            'character varying(max)' => 'VARCHAR',
            'character varying(% byte)' => 'VARCHAR',
            'char(% byte)' => 'CHAR',
            'char large object' => 'CLOB',
            'char large object(%)' => 'CLOB',
            'char varying' => 'VARCHAR',
            'char varying(%)' => 'VARCHAR',
            'char varying(max)' => 'VARCHAR',
            'char varying(% byte)' => 'VARCHAR',
            'char (% byte)' => 'CHAR',
            'char (% char)' => 'CHAR',
            'cidr' => 'VARCHAR',
            'circle' => 'OBJECT',
            'clob' => 'CLOB',
            'clob(%)' => 'CLOB',
            'date' => 'DATE',
            'datetime' => 'TIMESTAMP',
            'datetime2' => 'TIMESTAMP',
            'datetime2(%)' => 'TIMESTAMP',
            'datetimeoffset' => 'TIMESTAMP',
            'datetimeoffset(%)' => 'TIMESTAMP',
            'dbclob(%)' => 'CLOB',
            'dec' => 'DECIMAL',
            'dec(%,%)' => 'DECIMAL',
            'dec(%)' => 'DECIMAL',
            'decfloat' => 'FLOAT',
            'decfloat(%)' => 'FLOAT',
            'decimal' => 'DECIMAL',
            'decimal(%,%)' => 'DECIMAL',
            'decimal(%)' => 'DECIMAL',
            'double' => 'DOUBLE',
            'double(%,%)' => 'DOUBLE',
            'double precision' => 'DOUBLE',
            'float' => 'FLOAT',
            'float(%,%)' => 'FLOAT',
            'float(%)' => 'FLOAT',
            'float4' => 'FLOAT',
            'float8' => 'FLOAT',
            'geography' => 'OBJECT',
            'geometry' => 'OBJECT',
            'graphic' => 'BLOB',
            'graphic(%)' => 'BLOB',
            'hierarchyid' => 'VARCHAR',
            'image' => 'BLOB',
            'inet' => 'VARCHAR',
            'int' => 'INTEGER',
            'int(%)'  => 'INTEGER',
            'int2' => 'INTEGER',
            'int4' => 'INTEGER',
            'int8' => 'INTEGER',
            'integer' => 'INTEGER',
            'integer(%)' => 'INTEGER',
            'integer(%) unsigned' => 'INTEGER',
            'integer unsigned' => 'INTEGER',
            'integer(%) unsigned zerofill' => 'INTEGER',
            'integer unsigned zerofill' => 'INTEGER',
            'integer(%) zerofill' => 'INTEGER',
            'integer zerofill' => 'INTEGER',
            'interval' => 'VARCHAR',
            'interval day to second' => 'VARCHAR',
            'interval day to second (%)' => 'VARCHAR',
            'interval day (%) to second' => 'VARCHAR',
            'interval day (%) to second (%)' => 'VARCHAR',
            'interval year to month' => 'VARCHAR',
            'interval year (%) to month' => 'VARCHAR',
            'int(%) unsigned' => 'INTEGER',
            'int unsigned' => 'INTEGER',
            'int(%) unsigned zerofill' => 'INTEGER',
            'int unsigned zerofill' => 'INTEGER',
            'int(%) zerofill' => 'INTEGER',
            'int zerofill' => 'INTEGER',
            'json' => 'VARCHAR',
            'line' => 'OBJECT',
            'long' => 'LONGVARCHAR',
            'longblob' => 'LONGVARBINARY',
            'longtext' => 'CLOB',
            'longvarbinary' => 'CLOB',
            'longvarbinary(%)'=> 'CLOB',
            'longvarchar' => 'LONGVARCHAR',
            'longvarchar(%)'=> 'LONGVARCHAR',
            'long raw' => 'LONGVARCHAR',
            'lseg' => 'OBJECT',
            'macaddr' => 'OBJECT',
            'mediumblob' => 'VARBINARY',
            'mediumint' => 'INTEGER',
            'mediumint(%)' => 'INTEGER',
            'mediumint(%) unsigned' => 'INTEGER',
            'mediumint unsigned' => 'INTEGER',
            'mediumint(%) unsigned zerofill' => 'INTEGER',
            'mediumint unsigned zerofill' => 'INTEGER',
            'mediumint(%) zerofill' => 'INTEGER',
            'mediumint zerofill' => 'INTEGER',
            'mediumtext' => 'CLOB',
            'money' => 'DECIMAL',
            'national char' => 'CHAR',
            'national char(%)' => 'CHAR',
            'national character' => 'CHAR',
            'national character(%)' => 'CHAR',
            'national character (%)' => 'CHAR',
            'national character varying' => 'VARCHAR',
            'national character varying(%)' => 'VARCHAR',
            'national character varying(max)' => 'VARCHAR',
            'national char (%)' => 'CHAR',
            'national char varying' => 'VARCHAR',
            'national char varying(%)' => 'VARCHAR',
            'national char varying(max)' => 'VARCHAR',
            'native character(%)' => 'CHAR',
            'nchar' => 'CHAR',
            'nchar(%)' => 'CHAR',
            'nchar varying(%)' => 'VARCHAR',
            'nclob' => 'CLOB',
            'ntext' => 'CLOB',
            'num' => 'DOUBLE',
            'num(%,%)' => 'DOUBLE',
            'num(%)' => 'DOUBLE',
            'number' => 'DOUBLE',
            'number(%,%)' => 'DOUBLE',
            'number(%)' => 'DOUBLE',
            'numeric' => 'DECIMAL',
            'numeric(%,%)' => 'DECIMAL',
            'numeric(%)' => 'DECIMAL',
            'nvarchar' => 'VARCHAR',
            'nvarchar(%)'=> 'VARCHAR',
            'nvarchar2(%)'=> 'VARCHAR',
            'nvarchar(max)'=> 'VARCHAR',
            'oid' => 'BLOB',
            'path' => 'OBJECT',
            'point'=> 'OBJECT',
            'polygon' => 'OBJECT',
            'raw(%)' => 'BLOB',
            'real' => 'REAL',
            'real(%,%)' => 'REAL',
            'rowid' => 'INTEGER',
            'rowversion' => 'INTEGER',
            'serial' => 'INTEGER',
            'serial8' => 'INTEGER',
            'smalldatetime' => 'TIMESTAMP',
            'smallint' => 'SMALLINT',
            'smallint(%)' => 'SMALLINT',
            'smallint(%) unsigned' => 'SMALLINT',
            'smallint unsigned' => 'SMALLINT',
            'smallint(%) unsigned zerofill' => 'SMALLINT',
            'smallint unsigned zerofill' => 'SMALLINT',
            'smallint(%) zerofill' => 'SMALLINT',
            'smallint zerofill' => 'SMALLINT',
            'smallmoney' => 'DECIMAL',
            'sql_variant' => 'VARCHAR',
            'text' => 'LONGVARCHAR',
            'time' => 'TIME',
            'time(%)' => 'TIME',
            'timestamp' => 'TIMESTAMP',
            'timestamp(%)' => 'TIMESTAMP',
            'timestamptz' => 'TIMESTAMP',
            'timestamp(%) without time zone' => 'TIMESTAMP',
            'timestamp without time zone' => 'TIMESTAMP',
            'timestamp with local time zone' => 'TIMESTAMP',
            'timestamp(%) with time zone' => 'TIMESTAMP',
            'timestamp with time zone' => 'TIMESTAMP',
            'timestamp (%) with local time zone' => 'TIMESTAMP',
            'timetz' => 'TIME',
            'time(%) without time zone' => 'TIME',
            'time without time zone' => 'TIME',
            'time(%) with time zone' => 'TIME',
            'time with time zone' => 'TIME',
            'tinyblob' => 'BLOB',
            'tinyint' => 'TINYINT',
            'tinyint(%)' => 'TINYINT',
            'tinyint(%) unsigned' => 'TINYINT',
            'tinyint unsigned' => 'TINYINT',
            'tinyint(%) unsigned zerofill' => 'TINYINT',
            'tinyint unsigned zerofill' => 'TINYINT',
            'tinyint(%) zerofill' => 'TINYINT',
            'tinyint zerofill' => 'TINYINT',
            'tinytext' => 'CLOB',
            'tsquery' => 'VARCHAR',
            'tsvector' => 'OBJECT',
            'txid_snapshot' => 'VARCHAR',
            'uniqueidentifier' => 'VARCHAR',
            'unsigned big int' => 'BIGINT',
            'uritype' => 'VARCHAR',
            'urowid' => 'VARCHAR',
            'urowid(%)' => 'VARCHAR',
            'uuid' => 'VARCHAR',
            'varbinary' => 'BLOB',
            'varbinary(%)' => 'BLOB',
            'varbinary(max)' => 'BLOB',
            'varchar' => 'VARCHAR',
            'varchar(%)' => 'VARCHAR',
            'varchar2(%)' => 'VARCHAR',
            'varchar2(% byte)' => 'VARCHAR',
            'varchar2(% char)' => 'VARCHAR',
            'varchar(max)' => 'VARCHAR',
            'varchar(% byte)' => 'VARCHAR',
            'vargraphic' => 'BLOB',
            'vargraphic(%)' => 'BLOB',
            'varying character(%)' => 'VARCHAR',
            'xml' => 'VARCHAR',
            'year' => 'VARCHAR'
            ];
    }
}